// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class document_table_Add_ok_güncelleme_2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(document_table_Add_ok_güncelleme_2));
        
        string IMigrationMetadata.Id
        {
            get { return "202212081839476_document_table_Add_ok_güncelleme_2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
